import { Flex, Text, Image } from "@chakra-ui/react";
import React from "react";
import theme from "../../theme/index";
import LYDATeam from "../../assets/LYDATeam.png";
import Song from "../../assets/Song.png";
export const InfoLayout = () => {
  return (
    <Flex
      bg={"white.0"}
      h={"100%"}
      pt="120px"
      pb="125px"
      w="100%"
      fontFamily={theme.fonts.main}
    >
      <Flex flexDir={"column"} w="100%" color={"blue.200"}>
        <Flex
          w="100%"
          justifyContent={"center"}
          alignItems="center"
          mb={"120px"}
        >
          <Image src={LYDATeam} mr={"100px"} h={"584px"} w={"568px"} />
          <Flex flexDir={"column"}>
            <Text fontSize={"40px"} fontWeight={600} mb={"24px"}>
              Founded in 2022,
            </Text>
            <Text
              w="500px"
              fontSize={"18px"}
              fontStyle="normal"
              fontWeight={400}
              lineHeight={'32px'}
            >
              LYDA is a social token platform that quantifies the social capital
              generated by the fandoms of digital content creators, and converts
              said social capital into real capital in an effort to financially
              support creators and sustain a circulating economic structure. By
              enabling fandom-based social capital, fans may actively contribute
              to the longevity of their favorite brand’s business while being
              rewarded for their active participation in the community. To
              achieve this, LYDA platform offers creators the opportunity to
              create their own social token and build a community economy. In
              doing so, LYDA reduces the Web3 barrier to entry for creators
              while providing functions that that directly connect individuals
              to their fandoms main stakeholder.
            </Text>
          </Flex>
        </Flex>
        <Flex w="100%" justifyContent={"center"} alignItems="center">
          <Flex flexDir={"column"}>
            <Text
              color="#666d8b"
              fontSize={"18px"}
              fontStyle="normal"
              fontWeight={600}
            >
              Project Director
            </Text>
            <Text
              fontSize={"40px"}
              fontWeight={600}
              mb={"24px"}
              lineHeight="63px"
            >
              Seong Song
            </Text>
            <Text  w="500px"
              fontSize={"18px"}
              fontStyle="normal"
              lineHeight={'32px'}
              fontWeight={400}>
              Bio: Onther, standing for “On Ethereum,” is an Ethereum Layer-2
              blockchain research and development company. Onther utilizes the
              Tokamak Network to launch new projects via it’s TONstarter
              platform in an effort to easily build trustless blockchain
              applications.{" "}
            </Text>
          </Flex>
          <Image src={Song} ml={"100px"} h={"584px"} w={"568px"} />
        </Flex>
      </Flex>
    </Flex>
  );
};
